repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml

      - id: end-of-file-fixer

      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npm run lint
        language: system
        pass_filenames: false

      - id: prettier
        name: prettier
        entry: npx prettier --write .
        language: system
        pass_filenames: false
