// One-off generator: downloads free-exercise-db, merges RU names/aliases from
// scripts/data/exercise-ru.json, writes a SQL migration. Dedup against rows
// already in the DB happens inside the generated SQL (where not exists), so
// this script needs no DB access. Run: npx tsx scripts/import-free-exercise-db.ts
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  isImportable,
  rowToSqlValues,
  sqlQuote,
  sqlTextArray,
  toImportedRow,
  type RuEntry,
  type SourceExercise,
} from '../src/lib/utils/exercise-import'

const SOURCE_URL =
  'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json'
const here = dirname(fileURLToPath(import.meta.url))
const MIGRATION_PATH = join(
  here,
  '..',
  'supabase',
  'migrations',
  '20260719120000_import_free_exercise_db.sql',
)
const RU_PATH = join(here, 'data', 'exercise-ru.json')

async function main() {
  const res = await fetch(SOURCE_URL)
  if (!res.ok) throw new Error(`download failed: HTTP ${res.status}`)
  const all = (await res.json()) as SourceExercise[]
  const ru = JSON.parse(readFileSync(RU_PATH, 'utf8')) as Record<string, RuEntry>

  const importable = all.filter(isImportable)
  const missing = importable.filter((e) => !ru[e.name]).map((e) => e.name)
  if (missing.length > 0) {
    console.error(`Missing RU entries: ${missing.length}`)
    for (const name of missing.sort()) console.error('  ' + name)
    process.exit(1)
  }

  const rows = importable.map((e) => toImportedRow(e, ru[e.name]))
  const values = rows.map(rowToSqlValues).join(',\n')
  const backfill = rows
    .filter((r) => r.image_urls.length > 0)
    .map((r) => `(${sqlQuote(r.name)}, ${sqlTextArray(r.image_urls)})`)
    .join(',\n')

  const sql = `-- Generated by scripts/import-free-exercise-db.ts — do not edit by hand.
-- Source: free-exercise-db (public domain). ${rows.length} exercises after
-- filtering (categories stretching/cardio and unmappable muscles skipped).
-- Dedup: rows matching an existing built-in exercise by name or slug are
-- skipped; their photos are backfilled onto the existing row below.

insert into exercises
  (name, slug, primary_muscle, secondary_muscles, mechanic, equipment,
   is_custom, created_by, name_ru, aliases, instructions_en, image_urls)
select
  v.name, v.slug, v.primary_muscle::muscle_group,
  v.secondary_muscles::muscle_group[], v.mechanic, v.equipment::equipment_type,
  false, null, v.name_ru, v.aliases, v.instructions_en, v.image_urls
from (values
${values}
) as v(name, slug, primary_muscle, secondary_muscles, mechanic, equipment,
       name_ru, aliases, instructions_en, image_urls)
where not exists (
  select 1 from exercises e
  where e.is_custom = false
    and (lower(e.name) = lower(v.name) or e.slug = v.slug)
);

-- Backfill photos onto pre-existing rows that match by name and have none.
update exercises e
set image_urls = v.image_urls
from (values
${backfill}
) as v(name, image_urls)
where lower(e.name) = lower(v.name)
  and e.is_custom = false
  and coalesce(array_length(e.image_urls, 1), 0) = 0;
`
  writeFileSync(MIGRATION_PATH, sql, 'utf8')
  console.log(`OK: ${rows.length} exercises -> ${MIGRATION_PATH}`)
}

void main()
